In [2]:
import qubx
from qubx import logger

%qubxd

%load_ext autoreload
%autoreload 2

from qubx.core.lookups import lookup
from qubx.data.registry import StorageRegistry
from qubx.data.storages.multi import MultiStorage

⠀⠀⡰⡖⠒⠒⢒⢦⠀⠀
⠀⢠⠃⠈⢆⣀⣎⣀⣱⡀  QUBX | Quantitative Backtesting Environment
⠀⢳⠒⠒⡞⠚⡄⠀⡰⠁         (c) 2025, ver. 0.7.40.dev8
⠀⠀⠱⣜⣀⣀⣈⣦⠃⠀⠀⠀

In [36]:
stor = StorageRegistry.get("ccxt")
r = stor.get_reader("BINANCE.UM", "SWAP")
r1 = stor.get_reader("HYPERLIQUID", "SWAP")

In [37]:
r.get_data_types("BTCUSDT")

[ohlc, funding_payment]

In [7]:
r.read("BTCUSDT", "ohlc(1h)", "-12h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-02-23 02:00:00,64387.2,64877.2,64273.8,64742.4,14329.587,9.277319e+08
2026-02-23 03:00:00,64742.5,65071.7,64658.0,64894.0,7843.597,5.090024e+08
2026-02-23 04:00:00,64894.1,64989.9,64628.5,64777.3,4946.411,3.204151e+08
2026-02-23 05:00:00,64777.2,65189.3,64768.8,65031.9,6877.930,4.472849e+08
2026-02-23 06:00:00,65031.9,65775.0,64990.8,65717.7,11459.287,7.530780e+08
2026-02-23 07:00:00,65717.7,65980.0,65597.5,65915.8,8197.238,5.403275e+08
2026-02-23 08:00:00,65915.7,65922.9,65534.6,65639.0,6455.790,4.237516e+08
2026-02-23 09:00:00,65639.0,66432.9,65633.8,66374.8,11681.811,7.753779e+08
2026-02-23 10:00:00,66374.9,66574.5,66182.4,66291.1,7254.377,4.809006e+08
2026-02-23 11:00:00,66291.2,66462.1,66072.5,66170.8,5334.809,3.530086e+08
2026-02-23 12:00:00,66170.8,66490.0,65860.9,66249.9,10192.338,6.752414e+08
2026-02-23 13:00:00,66250.0,66360.1,66079.3,66199.0,4823.057,3.192816e+08

In [38]:
r1.read("BTCUSDC", "ohlc(1h)", "-3h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-02-23 11:00:00,66290.0,66455.0,66065.0,66166.0,1287.62455,8.519697e+07
2026-02-23 12:00:00,66166.0,66472.0,65857.0,66235.0,1997.77033,1.323223e+08
2026-02-23 13:00:00,66236.0,66408.0,66085.0,66250.0,963.86480,6.385604e+07

In [39]:
r.read("BTCUSDT", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-22 16:00:00      0.000050                     8.0
2026-02-23 00:00:00      0.000069                     8.0
2026-02-23 08:00:00     -0.000093                     8.0

In [40]:
r1.read("BTCUSDC", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-22 14:00:00  1.250000e-05                     1.0
2026-02-22 15:00:00  8.985200e-06                     1.0
2026-02-22 16:00:00  1.206660e-05                     1.0
2026-02-22 17:00:00  8.091000e-06                     1.0
2026-02-22 18:00:00  4.969000e-07                     1.0
2026-02-22 19:00:00  6.217100e-06                     1.0
2026-02-22 20:00:00  6.507400e-06                     1.0
2026-02-22 21:00:00  4.425800e-06                     1.0
2026-02-22 22:00:00  9.820000e-07                     1.0
2026-02-22 23:00:00 -1.592300e-06                     1.0
2026-02-23 00:00:00 -5.946400e-06                     1.0
2026-02-23 01:00:00 -9.565200e-06                     1.0
2026-02-23 02:00:00  5.847200e-06                     1.0
2026-02-23 03:00:00  5.934500e-06                     1.0
2026-02-23 04:00:00  5.413500e-06                     1.0
2026-02-23 05:00:00  5.600900e-06                     1.0
2026-02-23 06:00:00  1.100230e-05                     1.0
2026-02-23 07:00:00  6.449800e-06                     1.0
2026-02-23 08:00:00  8.224600e-06                     1.0
2026-02-23 09:00:00  5.976600e-06                     1.0
2026-02-23 10:00:00  7.661000e-06                     1.0
2026-02-23 11:00:00  6.123000e-07                     1.0
2026-02-23 12:00:00 -5.011600e-06                     1.0
2026-02-23 13:00:00 -8.376300e-06                     1.0

In [42]:
stor1 = StorageRegistry.get("ccxt")
stor2 = StorageRegistry.get("qdb::quantlab")

In [43]:
s2 = MultiStorage(storages=[stor1, stor2])
rx = s2.get_reader("BINANCE.UM", "SWAP")

In [44]:
%%time
rx.read(["BTCUSDT", "ETHUSDT"], "ohlc(1min)", "-2d", "now").to_pd()

CPU times: user 234 ms, sys: 3.45 ms, total: 237 ms
Wall time: 1.87 s

                     BTCUSDT                                                   \
                        open     high      low    close  volume  quote_volume
timestamp
2026-02-21 13:56:00  68177.4  68183.8  68174.4  68174.4   8.716  5.942474e+05
2026-02-21 13:57:00  68174.4  68197.8  68174.4  68187.3  30.553  2.083350e+06
2026-02-21 13:58:00  68187.4  68213.0  68187.3  68213.0  26.750  1.824436e+06
2026-02-21 13:59:00  68213.0  68229.6  68207.7  68223.3  44.935  3.065622e+06
2026-02-21 14:00:00  68223.3  68223.3  68209.0  68209.1  21.666  1.477952e+06
...                      ...      ...      ...      ...     ...           ...
2026-02-23 13:51:00  66325.0  66325.1  66287.4  66299.1  43.175  2.862464e+06
2026-02-23 13:52:00  66299.1  66339.9  66284.1  66286.6  58.594  3.883997e+06
2026-02-23 13:53:00  66286.5  66316.8  66280.2  66285.2  53.382  3.538437e+06
2026-02-23 13:54:00  66285.2  66291.3  66224.7  66224.8  83.074  5.501559e+06
2026-02-23 13:55:00  66224.8  66224.8  66218.1  66224.7  11.080  7.337697e+05

                     ETHUSDT                                       \
                        open     high      low    close    volume
timestamp
2026-02-21 13:56:00  1978.43  1978.44  1978.37  1978.39   521.170
2026-02-21 13:57:00  1978.39  1979.21  1978.38  1978.76   901.197
2026-02-21 13:58:00  1978.77  1980.02  1978.76  1979.73  2033.407
2026-02-21 13:59:00  1979.73  1980.68  1979.72  1980.22  1335.280
2026-02-21 14:00:00  1980.21  1980.37  1979.84  1979.89  1263.385
...                      ...      ...      ...      ...       ...
2026-02-23 13:51:00  1928.76  1928.84  1926.98  1927.76  2482.000
2026-02-23 13:52:00  1927.75  1929.52  1927.75  1928.33  7208.017
2026-02-23 13:53:00  1928.33  1928.75  1927.22  1927.63  3505.590
2026-02-23 13:54:00  1927.63  1928.00  1924.79  1924.79  4051.930
2026-02-23 13:55:00  1924.79  1924.80  1924.11  1924.68   916.031


                     quote_volume
timestamp
2026-02-21 13:56:00  1.031085e+06
2026-02-21 13:57:00  1.783306e+06
2026-02-21 13:58:00  4.024914e+06
2026-02-21 13:59:00  2.644244e+06
2026-02-21 14:00:00  2.501677e+06
...                           ...
2026-02-23 13:51:00  4.784700e+06
2026-02-23 13:52:00  1.389944e+07
2026-02-23 13:53:00  6.757480e+06
2026-02-23 13:54:00  7.799114e+06
2026-02-23 13:55:00  1.763067e+06

[2880 rows x 12 columns]

In [45]:
rx.read("BTCUSDT", "funding_payment", "-3d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-20 16:00:00 -6.710000e-06                     8.0
2026-02-21 00:00:00  4.456000e-05                     8.0
2026-02-21 08:00:00  2.485000e-05                     8.0
2026-02-21 16:00:00  3.235000e-05                     8.0
2026-02-22 00:00:00  7.300000e-06                     8.0
2026-02-22 08:00:00 -4.000000e-08                     8.0
2026-02-22 16:00:00  4.972000e-05                     8.0
2026-02-23 00:00:00  6.957000e-05                     8.0
2026-02-23 08:00:00 -9.317000e-05                     8.0

BTCUSDT(funding_payment)[2026-01-10 00:00:00 : 2026-02-19 16:00:00] : (123 x 4)

In [33]:
stor = StorageRegistry.get("qdb::quantlab")
r = stor.get_reader("GATEIO.F", "SWAP")
w = r.read("BTCUSDT", "funding_payment", "2026-01-10 00:00:00", "2026-02-20 00:00:00", chunksize=100)
# w
# next(w)

In [76]:
fr = stor.get_reader("BINANCE.UM", "SWAP")

In [ ]:
# fundamental = fr.read(["BTCUSDT"], "funding_payment", "2026-01-01", "2026-01-10").to_pd(False)

funding_payments = fr.read([], "funding_payment", "2026-01-01", "2026-01-10").to_pd(True)
# if funding_payments is None or funding_payments.empty:
    # return []
earliest_payment_time = funding_payments.reset_index().groupby("symbol")["timestamp"].min()
earliest_payment_time = earliest_payment_time[
    earliest_payment_time <= min_maturity_date + pd.Timedelta(hours=10)
]  # type: ignore

In [88]:
funding_payments

                                    funding_rate  funding_interval_hours
timestamp           symbol
2026-01-01 00:00:00 0GUSDT             -0.001422                     4.0
                    1000000BOBUSDT      0.002340                     4.0
                    1000000MOGUSDT      0.000050                     4.0
                    1000BONKUSDC        0.000050                     4.0
                    1000BONKUSDT        0.000020                     4.0
...                                          ...                     ...
2026-01-09 23:00:00 FLOWUSDT           -0.000305                     1.0
                    GMTUSDT            -0.000454                     8.0
                    PIPPINUSDT         -0.000542                     1.0
                    RIVERUSDT           0.000230                     1.0
                    ZKPUSDT            -0.000085                     1.0

[28598 rows x 2 columns]

In [87]:
earliest_payment_time

symbol
0GUSDT           2026-01-01
1000000BOBUSDT   2026-01-01
1000000MOGUSDT   2026-01-01
1000BONKUSDC     2026-01-01
1000BONKUSDT     2026-01-01
                    ...
ZORAUSDT         2026-01-01
ZRCUSDT          2026-01-01
ZROUSDT          2026-01-01
ZRXUSDT          2026-01-01
币安人生USDT         2026-01-01
Name: timestamp, Length: 580, dtype: datetime64[us]

In [83]:
fundamental

                     BTCUSDT
                      symbol funding_rate funding_interval_hours
timestamp
2026-01-01 00:00:00  BTCUSDT     0.000100                    8.0
2026-01-01 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-01 16:00:00  BTCUSDT     0.000018                    8.0
2026-01-02 00:00:00  BTCUSDT     0.000056                    8.0
2026-01-02 08:00:00  BTCUSDT     0.000042                    8.0
2026-01-02 16:00:00  BTCUSDT     0.000048                    8.0
2026-01-03 00:00:00  BTCUSDT     0.000031                    8.0
2026-01-03 08:00:00  BTCUSDT     0.000011                    8.0
2026-01-03 16:00:00  BTCUSDT     0.000069                    8.0
2026-01-04 00:00:00  BTCUSDT     0.000095                    8.0
2026-01-04 08:00:00  BTCUSDT     0.000058                    8.0
2026-01-04 16:00:00  BTCUSDT     0.000044                    8.0
2026-01-05 00:00:00  BTCUSDT     0.000089                    8.0
2026-01-05 08:00:00  BTCUSDT     0.000052                    8.0
2026-01-05 16:00:00  BTCUSDT     0.000078                    8.0
2026-01-06 00:00:00  BTCUSDT    -0.000014                    8.0
2026-01-06 08:00:00  BTCUSDT     0.000028                    8.0
2026-01-06 16:00:00  BTCUSDT     0.000027                    8.0
2026-01-07 00:00:00  BTCUSDT     0.000066                    8.0
2026-01-07 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-07 16:00:00  BTCUSDT     0.000029                    8.0
2026-01-08 00:00:00  BTCUSDT     0.000087                    8.0
2026-01-08 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-08 16:00:00  BTCUSDT     0.000064                    8.0
2026-01-09 00:00:00  BTCUSDT    -0.000028                    8.0
2026-01-09 08:00:00  BTCUSDT     0.000073                    8.0
2026-01-09 16:00:00  BTCUSDT     0.000002                    8.0

In [66]:
mcap = fundamental.xs("market_cap", axis=1, level=1).mean(axis=0).sort_values(ascending=False)

In [68]:
mcap.index

Index(['BTC', 'ETH', 'USDT', 'XRP', 'BNB', 'SOL', 'USDC', 'TRX', 'DOGE', 'ADA',
       ...
       'ORD', '1MBABYDOGE', 'HIGH', 'AEUR', 'EURI', 'MKR', 'AGT', 'FTM', 'HIP',
       'FTT'],
      dtype='object', length=865)

In [ ]:
fundamental.xs(("asset", "market_cap"), axis=1)

In [32]:
next(w).to_records()[0].time

StopIteration: