In [3]:
import qubx
from qubx import logger

%qubxd

%load_ext autoreload
%autoreload 2

from qubx.core.lookups import lookup
from qubx.data.registry import StorageRegistry
from qubx.data.storages.multi import MultiStorage

⠀⠀⡰⡖⠒⠒⢒⢦⠀⠀
⠀⢠⠃⠈⢆⣀⣎⣀⣱⡀  QUBX | Quantitative Backtesting Environment
⠀⢳⠒⠒⡞⠚⡄⠀⡰⠁         (c) 2025, ver. 1.0.0.dev2
⠀⠀⠱⣜⣀⣀⣈⣦⠃⠀⠀⠀

In [4]:
stor = StorageRegistry.get("ccxt")
r = stor.get_reader("BINANCE.UM", "SWAP")
r1 = stor.get_reader("HYPERLIQUID", "SWAP")

In [13]:
r.get_data_types("BTCUSDT")

[ohlc, funding_payment]

In [14]:
r.read("BTCUSDT", "ohlc(1h)", "-12h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-03-02 04:00:00,66787.3,66950.0,66600.1,66825.1,4900.156,3.274534e+08
2026-03-02 05:00:00,66825.2,66966.0,66513.8,66701.2,4040.023,2.694744e+08
2026-03-02 06:00:00,66701.2,66703.1,66015.0,66176.9,6189.233,4.095843e+08
2026-03-02 07:00:00,66176.8,66182.9,65509.0,65981.3,8780.148,5.793256e+08
2026-03-02 08:00:00,65981.2,66279.2,65612.4,66247.9,7684.981,5.091139e+08
2026-03-02 09:00:00,66247.9,66707.5,66118.8,66132.3,8485.670,5.611769e+08
2026-03-02 10:00:00,66132.3,66368.5,66039.6,66284.0,3720.637,2.466187e+08
2026-03-02 11:00:00,66284.0,66455.7,65973.1,66329.9,5955.186,3.950069e+08
2026-03-02 12:00:00,66329.8,66369.1,65879.6,65927.8,4353.668,2.870278e+08
2026-03-02 13:00:00,65927.7,66111.9,65319.9,65412.3,10340.986,6.764277e+08
2026-03-02 14:00:00,65412.3,67188.0,65234.4,67128.7,27469.276,1.843977e+09
2026-03-02 15:00:00,67128.6,69588.0,66911.2,68935.0,57102.573,3.936366e+09

In [16]:
r1.read("BTCUSDC", "ohlc(1h)", "-3h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-03-02 13:00:00,65933.0,66102.0,65323.0,65414.0,2160.39544,1.413201e+08
2026-03-02 14:00:00,65414.0,67214.0,65250.0,67142.0,5138.42804,3.450043e+08
2026-03-02 15:00:00,67142.0,69597.0,66954.0,68837.0,10291.74224,7.084527e+08

In [17]:
r.read("BTCUSDT", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-03-01 16:00:00      0.000029                     8.0
2026-03-02 00:00:00     -0.000003                     8.0
2026-03-02 08:00:00     -0.000020                     8.0

In [18]:
r1.read("BTCUSDC", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-03-01 16:00:00  3.303400e-06                     1.0
2026-03-01 17:00:00 -2.759700e-06                     1.0
2026-03-01 18:00:00 -5.468700e-06                     1.0
2026-03-01 19:00:00 -7.147200e-06                     1.0
2026-03-01 20:00:00 -8.194000e-06                     1.0
2026-03-01 21:00:00 -1.576520e-05                     1.0
2026-03-01 22:00:00 -1.731200e-05                     1.0
2026-03-01 23:00:00 -1.335770e-05                     1.0
2026-03-02 00:00:00 -3.880600e-06                     1.0
2026-03-02 01:00:00  3.177800e-06                     1.0
2026-03-02 02:00:00  3.731000e-06                     1.0
2026-03-02 03:00:00  7.087000e-07                     1.0
2026-03-02 04:00:00  4.300200e-06                     1.0
2026-03-02 05:00:00  5.105500e-06                     1.0
2026-03-02 06:00:00  2.464800e-06                     1.0
2026-03-02 07:00:00 -1.407850e-05                     1.0
2026-03-02 08:00:00 -4.619700e-06                     1.0
2026-03-02 09:00:00 -4.493000e-07                     1.0
2026-03-02 10:00:00 -2.478100e-06                     1.0
2026-03-02 11:00:00 -1.753200e-06                     1.0
2026-03-02 12:00:00 -8.150000e-07                     1.0
2026-03-02 13:00:00 -6.127000e-06                     1.0
2026-03-02 14:00:00  2.012000e-07                     1.0
2026-03-02 15:00:00  5.816200e-06                     1.0

In [19]:
stor1 = StorageRegistry.get("ccxt")
stor2 = StorageRegistry.get("qdb::quantlab")

In [20]:
s2 = MultiStorage(storages=[stor1, stor2])
rx = s2.get_reader("BINANCE.UM", "SWAP")

In [22]:
%%time
rx.read(["BTCUSDT", "ETHUSDT"], "ohlc(1min)", "-2d", "now").to_pd()

CPU times: user 231 ms, sys: 5.34 ms, total: 236 ms
Wall time: 2.06 s

                     BTCUSDT                                       \
                        open     high      low    close    volume
timestamp
2026-02-28 15:58:00  64822.7  64829.0  64810.0  64818.3    29.533
2026-02-28 15:59:00  64818.5  64822.5  64800.0  64800.0    26.060
2026-02-28 16:00:00  64800.1  64802.7  64766.9  64766.9    49.953
2026-02-28 16:01:00  64766.9  64771.9  64682.2  64691.7   150.756
2026-02-28 16:02:00  64691.7  64771.2  64691.7  64751.9    82.981
...                      ...      ...      ...      ...       ...
2026-03-02 15:53:00  69182.6  69201.7  68876.2  68886.4  1513.566
2026-03-02 15:54:00  68886.5  68962.5  68741.1  68929.4  1439.154
2026-03-02 15:55:00  68929.5  69074.5  68872.8  69034.5   647.590
2026-03-02 15:56:00  69034.5  69139.1  68865.2  68908.3   994.511
2026-03-02 15:57:00  68908.3  68930.2  68848.1  68893.9   335.121

                                   ETHUSDT                             \
                     quote_volume     open     high      low    close
timestamp
2026-02-28 15:58:00  1.914412e+06  1898.28  1898.91  1897.17  1898.15
2026-02-28 15:59:00  1.689035e+06  1898.16  1898.33  1897.60  1897.78
2026-02-28 16:00:00  3.236132e+06  1897.77  1897.77  1895.26  1895.51
2026-02-28 16:01:00  9.757660e+06  1895.50  1896.75  1893.39  1893.90
2026-02-28 16:02:00  5.371427e+06  1893.91  1895.79  1893.32  1895.39
...                           ...      ...      ...      ...      ...
2026-03-02 15:53:00  1.042641e+08  2046.43  2046.91  2037.08  2037.75
2026-03-02 15:54:00  9.920002e+07  2037.76  2041.10  2034.27  2038.27
2026-03-02 15:55:00  4.470605e+07  2038.26  2043.70  2036.77  2043.58
2026-03-02 15:56:00  6.853006e+07  2043.59  2047.59  2042.15  2042.99
2026-03-02 15:57:00  2.308779e+07  2042.99  2043.36  2038.98  2041.19


                        volume  quote_volume
timestamp
2026-02-28 15:58:00   1725.484  3.275145e+06
2026-02-28 15:59:00    998.258  1.894587e+06
2026-02-28 16:00:00   1698.899  3.221669e+06
2026-02-28 16:01:00   2744.530  5.200233e+06
2026-02-28 16:02:00   3968.961  7.519080e+06
...                        ...           ...
2026-03-02 15:53:00  28404.550  5.788137e+07
2026-03-02 15:54:00  24361.698  4.965572e+07
2026-03-02 15:55:00  13406.201  2.739664e+07
2026-03-02 15:56:00  14461.195  2.954408e+07
2026-03-02 15:57:00   9224.987  1.882995e+07

[2880 rows x 12 columns]

In [23]:
rx.read("BTCUSDT", "funding_payment", "-3d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-27 16:00:00     -0.000007                     8.0
2026-02-28 00:00:00      0.000040                     8.0
2026-02-28 08:00:00     -0.000037                     8.0
2026-02-28 16:00:00     -0.000043                     8.0
2026-03-01 00:00:00     -0.000008                     8.0
2026-03-01 08:00:00      0.000046                     8.0
2026-03-01 16:00:00      0.000029                     8.0
2026-03-02 00:00:00     -0.000004                     8.0
2026-03-02 08:00:00     -0.000020                     8.0

### Misc tests

In [33]:
stor = StorageRegistry.get("qdb::quantlab")
r = stor.get_reader("GATEIO.F", "SWAP")
w = r.read("BTCUSDT", "funding_payment", "2026-01-10 00:00:00", "2026-02-20 00:00:00", chunksize=100)
# w
# next(w)

In [76]:
fr = stor.get_reader("BINANCE.UM", "SWAP")

In [ ]:
# fundamental = fr.read(["BTCUSDT"], "funding_payment", "2026-01-01", "2026-01-10").to_pd(False)

funding_payments = fr.read([], "funding_payment", "2026-01-01", "2026-01-10").to_pd(True)
# if funding_payments is None or funding_payments.empty:
    # return []
earliest_payment_time = funding_payments.reset_index().groupby("symbol")["timestamp"].min()
earliest_payment_time = earliest_payment_time[
    earliest_payment_time <= min_maturity_date + pd.Timedelta(hours=10)
]  # type: ignore

In [88]:
funding_payments

                                    funding_rate  funding_interval_hours
timestamp           symbol
2026-01-01 00:00:00 0GUSDT             -0.001422                     4.0
                    1000000BOBUSDT      0.002340                     4.0
                    1000000MOGUSDT      0.000050                     4.0
                    1000BONKUSDC        0.000050                     4.0
                    1000BONKUSDT        0.000020                     4.0
...                                          ...                     ...
2026-01-09 23:00:00 FLOWUSDT           -0.000305                     1.0
                    GMTUSDT            -0.000454                     8.0
                    PIPPINUSDT         -0.000542                     1.0
                    RIVERUSDT           0.000230                     1.0
                    ZKPUSDT            -0.000085                     1.0

[28598 rows x 2 columns]

In [87]:
earliest_payment_time

symbol
0GUSDT           2026-01-01
1000000BOBUSDT   2026-01-01
1000000MOGUSDT   2026-01-01
1000BONKUSDC     2026-01-01
1000BONKUSDT     2026-01-01
                    ...
ZORAUSDT         2026-01-01
ZRCUSDT          2026-01-01
ZROUSDT          2026-01-01
ZRXUSDT          2026-01-01
币安人生USDT         2026-01-01
Name: timestamp, Length: 580, dtype: datetime64[us]

In [83]:
fundamental

                     BTCUSDT
                      symbol funding_rate funding_interval_hours
timestamp
2026-01-01 00:00:00  BTCUSDT     0.000100                    8.0
2026-01-01 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-01 16:00:00  BTCUSDT     0.000018                    8.0
2026-01-02 00:00:00  BTCUSDT     0.000056                    8.0
2026-01-02 08:00:00  BTCUSDT     0.000042                    8.0
2026-01-02 16:00:00  BTCUSDT     0.000048                    8.0
2026-01-03 00:00:00  BTCUSDT     0.000031                    8.0
2026-01-03 08:00:00  BTCUSDT     0.000011                    8.0
2026-01-03 16:00:00  BTCUSDT     0.000069                    8.0
2026-01-04 00:00:00  BTCUSDT     0.000095                    8.0
2026-01-04 08:00:00  BTCUSDT     0.000058                    8.0
2026-01-04 16:00:00  BTCUSDT     0.000044                    8.0
2026-01-05 00:00:00  BTCUSDT     0.000089                    8.0
2026-01-05 08:00:00  BTCUSDT     0.000052                    8.0
2026-01-05 16:00:00  BTCUSDT     0.000078                    8.0
2026-01-06 00:00:00  BTCUSDT    -0.000014                    8.0
2026-01-06 08:00:00  BTCUSDT     0.000028                    8.0
2026-01-06 16:00:00  BTCUSDT     0.000027                    8.0
2026-01-07 00:00:00  BTCUSDT     0.000066                    8.0
2026-01-07 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-07 16:00:00  BTCUSDT     0.000029                    8.0
2026-01-08 00:00:00  BTCUSDT     0.000087                    8.0
2026-01-08 08:00:00  BTCUSDT     0.000100                    8.0
2026-01-08 16:00:00  BTCUSDT     0.000064                    8.0
2026-01-09 00:00:00  BTCUSDT    -0.000028                    8.0
2026-01-09 08:00:00  BTCUSDT     0.000073                    8.0
2026-01-09 16:00:00  BTCUSDT     0.000002                    8.0

In [66]:
mcap = fundamental.xs("market_cap", axis=1, level=1).mean(axis=0).sort_values(ascending=False)

In [68]:
mcap.index

Index(['BTC', 'ETH', 'USDT', 'XRP', 'BNB', 'SOL', 'USDC', 'TRX', 'DOGE', 'ADA',
       ...
       'ORD', '1MBABYDOGE', 'HIGH', 'AEUR', 'EURI', 'MKR', 'AGT', 'FTM', 'HIP',
       'FTT'],
      dtype='object', length=865)

In [ ]:
fundamental.xs(("asset", "market_cap"), axis=1)

In [ ]:
next(w).to_records()[0].time

In [2]:
stor = StorageRegistry.get("qdb::quantlab")
r = stor.get_reader("BINANCE.UM", "SWAP")

In [4]:
r.read("ADAUSDT", "ohlc(1d)", "120d", "2020-02-01 00:00:00.000").to_pd()

,symbol,open,high,low,close,volume,quote_volume,count,taker_buy_volume,taker_buy_quote_volume
timestamp,,,,,,,,,,
2020-01-31,ADAUSDT,0.0545,0.05559,0.05209,0.05387,244632624.0,13130602.0,40186,116954448.0,6287357.0