In [1]:
import numpy as np
import pandas as pd

import qubx  # type: ignore
import pyarrow as pa

%qubxd

%load_ext autoreload
%autoreload 2

# - - - - - - - - - -
from qubx.data.containers import RawData, RawMultiData

_mk_batch = lambda t,n: pa.RecordBatch.from_arrays([np.arange(t, t+n), np.arange(10.0 * t, 10.0 * t + n)], ["time", "value"])

⠀⠀⡰⡖⠒⠒⢒⢦⠀⠀
⠀⢠⠃⠈⢆⣀⣎⣀⣱⡀  QUBX | Quantitative Backtesting Environment
⠀⢳⠒⠒⡞⠚⡄⠀⡰⠁         (c) 2025, ver. 0.7.40.dev8
⠀⠀⠱⣜⣀⣀⣈⣦⠃⠀⠀⠀

### Common

In [2]:
pa.__version__

'15.0.2'

1. Play with pa

In [13]:
r1 = pa.RecordBatch.from_pandas(pd.DataFrame({"time": [1, 2, 3], "value": [4, 5, 6]}))
r2 = pa.RecordBatch.from_pandas(pd.DataFrame({"time": [11, 12, 13], "value": [24, 25, 26]}))

In [16]:
b1 = _mk_batch(1, 500)
b2 = _mk_batch(501, 500)
combined = pa.concat_tables([pa.Table.from_batches([b1]), pa.Table.from_batches([b2])]).combine_chunks().to_batches()[0] 
combined

pyarrow.RecordBatch
time: int64
value: double
----
time: [1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000]
value: [10,11,12,13,14,15,16,17,18,19,...,5500,5501,5502,5503,5504,5505,5506,5507,5508,5509]

### Working with Batches as some storage

In [232]:
batches = []
S = 5_000
for k in range(0, 10*S, S):
    batches.append(_mk_batch(k, S))

In [231]:
%%timeit
combined = pa.concat_tables([pa.Table.from_batches([b]) for b in batches]).combine_chunks().to_batches()[0]

56.8 μs ± 162 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [230]:
len(combined)

50000

In [ ]:
# for r in zip(*combined.to_pydict().values()):
#     break

In [ ]:
# for r in combined.to_pylist():
#     break

In [ ]:
t_c = combined.column("time").to_numpy(zero_copy_only=True)
v_c = combined.column("value").to_numpy(zero_copy_only=True)

In [238]:
_cs = 0 
for t,v in zip(t_c, v_c):
    _cs += v / (t + 1)
_cs

406444.6489152973

### RawData2

In [227]:
from qubx.data.storage import IDataTransformer, Transformable
from qubx.core.basics import DataType
import pyarrow as pa
from typing import Any
from qubx.data.storages.utils import find_time_col_idx

In [228]:
class RawData(Transformable):
    _create_key = object()
    __slots__ = ("data_id", "dtype", "raw", "_index")

    def __init__(self, data_id: str, dtype: DataType, record_batch: pa.RecordBatch, *, _key=None):
        if _key is not RawData._create_key:
            raise TypeError("Do not call RawData() directly, use RawData.from_*() methods")
        self.data_id = data_id
        self.dtype = dtype
        self.raw = record_batch
        self._index = find_time_col_idx(self.names)

    @property
    def names(self) -> list[str]:
        return list(self.raw.schema.names)

    @classmethod
    def from_record_batch(cls, data_id: str, dtype: DataType, data: pa.RecordBatch) -> "RawData":
        return cls(data_id, dtype, data, _key=cls._create_key)

    @classmethod
    def from_table(cls, data_id: str, dtype: DataType, data: pa.Table) -> "RawData":
        batches = data.combine_chunks().to_batches()
        batch = batches[0] if batches else pa.RecordBatch.from_pydict({n: [] for n in data.schema.names})
        return cls(data_id, dtype, batch, _key=cls._create_key)

    @classmethod
    def from_pandas(cls, data_id: str, dtype: DataType, data: pd.DataFrame | pd.Series) -> "RawData":
        if isinstance(data, pd.Series):
            _data = data.reset_index(name=data.name or "value")
            _data.columns = ["time", _data.columns[1]]
        else:
            _data = data.reset_index() if data.index.name else data
        return cls(data_id, dtype, pa.RecordBatch.from_pandas(_data), _key=cls._create_key)

    def __len__(self) -> int:
        return self.raw.num_rows

    def get_time_interval(self) -> tuple[int | None, int | None]:
        """
        Returns start and end timestamp from raw data
        """
        if len(self) == 0:
            return (None, None)
        _idx_col = self.raw.column(self._index)
        return (_idx_col[0].as_py(), _idx_col[-1].as_py())

    def transform(self, transformer: IDataTransformer) -> object:
        return transformer.process_data(self.data_id, self.dtype, self.raw, self.names, self._index)

    def __repr__(self) -> str:
        s, e = self.get_time_interval()
        _range = f"{s} : {e}" if s is not None else "EMPTY"
        return f"{self.data_id}({self.dtype})[{_range}] : ({len(self)} x {len(self.names)})"

In [229]:
RawData.from_record_batch("Test1", DataType.OHLC, combined)

Test1(ohlc)[0 : 49999] : (50000 x 2)

In [186]:
r1 = RawData.from_record_batch("x1", "ohlcv", _mk_batch(1, 500))
r2 = RawData.from_record_batch("x1", "ohlcv", _mk_batch(501, 1000))
print(r1)
print(r2)

print(
    RawData.from_pandas("X", "ohlc", pd.DataFrame({"date": [1, 2, 3], "value": [4, 5, 6]}).set_index("date")),
    "\n",
    RawData.from_pandas("X", "ohlc", pd.Series([1, 2, 3, 4], name="www"))
)

x1(ohlcv)[1 : 500] : (500 x 2)
x1(ohlcv)[501 : 1500] : (1000 x 2)
X(ohlc)[1 : 3] : (3 x 2)
 X(ohlc)[0 : 3] : (4 x 2)

In [204]:
t1 = pa.Table.from_pandas(pd.DataFrame({"date": [0, 2, 3, 4, 5, 6], "value": [11,22,33,44,55,66]}))
x1 = RawData.from_table("x1", "ohlcv", t1[0:4]).raw.to_pandas()
x2 = RawData.from_table("x1", "ohlcv", t1[3:]).raw.to_pandas()

In [223]:
x1

   date  value
0     0     11
1     2     22
2     3     33
3     4     44

In [222]:
x2

   date  value
0     4    999
1     5    999
2     6     66

In [188]:
RawData.from_pandas("X", "ohlc", pd.DataFrame({"date": [], "value": []}))

X(ohlc)[EMPTY] : (0 x 2)

### RawData with nones

In [2]:
from qubx.data.transformers import OHLCVSeries, TypedRecords
from qubx.core.basics import DataType

In [3]:
raw_data = RawData.from_pandas("X", "ohlc", pd.DataFrame({
    "time":["2020-01-01", "2020-01-02", "2020-01-03"], 
    "open":  [1,2,3],
    "high":  [1,2,3],
    "low":   [3,2,1],
    "close": [1,2,None],
    "count": [None,None,None],
    "volume": [None,None,None],
}))

In [4]:
raw_data.to_pd()

            open  high  low  close count volume
time
2020-01-01     1     1    3    1.0  None   None
2020-01-02     2     2    2    2.0  None   None
2020-01-03     3     3    1    NaN  None   None

In [5]:
raw_data.to_ohlc()

            open  high  low  close  volume  bought_volume  volume_quote  \
timestamp
2020-01-01   1.0   1.0  3.0    1.0     NaN            0.0           0.0
2020-01-02   2.0   2.0  2.0    2.0     NaN            0.0           0.0
2020-01-03   3.0   3.0  1.0    NaN     NaN            0.0           0.0

            bought_volume_quote  trade_count
timestamp
2020-01-01                  0.0          0.0
2020-01-02                  0.0          0.0
2020-01-03                  0.0          0.0

In [51]:

# ok, let's review build_snapshots in /home/quant0/devs/Qubx/src/qubx/data/storages/utils.py                                       
#   it's based on list[tuple] could we use columns from record banches instead ?

In [6]:
raw_data.to_records()[0].bought_volume

0.0

In [12]:
raw_data.to_ticks(daily_session_start_end="STOCKS")

[[2020-01-01T09:30:01.100000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-01T11:00:00.000000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-01T13:00:00.000000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-01T15:59:58.900000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-02T09:30:01.100000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T11:00:00.000000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T13:00:00.000000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T15:59:58.900000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-03T09:30:01.100000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-03T11:00:00.000000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-03T13:00:00.000000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-03T15:59:58.900000000]	nan (1000000000.00) | nan (1000000000.00)]

### RawMultiData

In [13]:
from qubx.data.containers import RawData, RawMultiData
from qubx.core.basics import DataType

In [14]:
d1 = RawData.from_pandas("X", "ohlc", pd.DataFrame({
        "y": [-1,-2,-3], "date": [1,2,3], "value": [11,22,33]
    }))
d2 = RawData.from_pandas("X2", "ohlc", pd.DataFrame({
        "y": [-1,-2,-3,0], "date": [12,22,32,55], "value": [11,22,33,99]
    }))

In [15]:
r1 = RawData.from_pandas(
    "TEST1",
    DataType.TRADE,
    pd.DataFrame({
        "price": [100,120,190], "time": [1000,2000,3000], "size": [0.5, 0.3, 1.5]
    })
)

In [16]:
dd = r1.data

In [17]:
dd.column_names

['price', 'time', 'size']

In [18]:
dm = RawMultiData([d1, d2])

In [22]:
dm.to_pd()

                                 X         X2
                                 y value    y value
date
1970-01-01 00:00:00.000000001 -1.0  11.0  NaN   NaN
1970-01-01 00:00:00.000000002 -2.0  22.0  NaN   NaN
1970-01-01 00:00:00.000000003 -3.0  33.0  NaN   NaN
1970-01-01 00:00:00.000000012  NaN   NaN -1.0  11.0
1970-01-01 00:00:00.000000022  NaN   NaN -2.0  22.0
1970-01-01 00:00:00.000000032  NaN   NaN -3.0  33.0
1970-01-01 00:00:00.000000055  NaN   NaN  0.0  99.0

In [23]:
from qubx.data.registry import StorageRegistry

In [24]:
r = StorageRegistry.get("qdb::quantlab")["BINANCE.UM", "SWAP"]

In [34]:
r.read("BTCUSDT", "ohlc(1h)", "-5d", "now").to_ticks()

[[2026-01-28T16:00:01.000000000]	89655.80000 (1000000000.00) | 89655.80000 (1000000000.00),
 [2026-01-28T16:24:00.000000000]	89718.90000 (1000000000.00) | 89718.90000 (1000000000.00),
 [2026-01-28T16:36:00.000000000]	89419.40000 (1000000000.00) | 89419.40000 (1000000000.00),
 [2026-01-28T16:59:59.000000000]	89588.80000 (1000000000.00) | 89588.80000 (1000000000.00),
 [2026-01-28T17:00:01.000000000]	89588.80000 (1000000000.00) | 89588.80000 (1000000000.00),
 [2026-01-28T17:24:00.000000000]	89238.80000 (1000000000.00) | 89238.80000 (1000000000.00),
 [2026-01-28T17:36:00.000000000]	90592.70000 (1000000000.00) | 90592.70000 (1000000000.00),
 [2026-01-28T17:59:59.000000000]	90142.90000 (1000000000.00) | 90142.90000 (1000000000.00),
 [2026-01-28T18:00:01.000000000]	90142.90000 (1000000000.00) | 90142.90000 (1000000000.00),
 [2026-01-28T18:24:00.000000000]	90149.20000 (1000000000.00) | 90149.20000 (1000000000.00),
 [2026-01-28T18:36:00.000000000]	89216.40000 (1000000000.00) | 89216.40000 (1000000000.00),
 [2026-01-28T18:59:59.000000000]	89501.00000 (1000000000.00) | 89501.00000 (1000000000.00),
 [2026-01-28T19:00:01.000000000]	89500.90000 (1000000000.00) | 89500.90000 (1000000000.00),
 [2026-01-28T19:24:00.000000000]	89693.90000 (1000000000.00) | 89693.90000 (1000000000.00),
 [2026-01-28T19:36:00.000000000]	88974.00000 (1000000000.00) | 88974.00000 (1000000000.00),
 [2026-01-28T19:59:59.000000000]	89363.60000 (1000000000.00) | 89363.60000 (1000000000.00),
 [2026-01-28T20:00:01.000000000]	89363.50000 (1000000000.00) | 89363.50000 (1000000000.00),
 [2026-01-28T20:24:00.000000000]	89880.10000 (1000000000.00) | 89880.10000 (1000000000.00),
 [2026-01-28T20:36:00.000000000]	88964.70000 (1000000000.00) | 88964.70000 (1000000000.00),
 [2026-01-28T20:59:59.000000000]	89099.90000 (1000000000.00) | 89099.90000 (1000000000.00),
 [2026-01-28T21:00:01.000000000]	89100.00000 (1000000000.00) | 89100.00000 (1000000000.00),
 [2026-01-28T21:24:00.000000000]	88829.00000 (1000000000.00) | 88829.00000 (1000000000.00),
 [2026-01-28T21:36:00.000000000]	89449.10000 (1000000000.00) | 89449.10000 (1000000000.00),
 [2026-01-28T21:59:59.000000000]	89369.30000 (1000000000.00) | 89369.30000 (1000000000.00),
 [2026-01-28T22:00:01.000000000]	89369.40000 (1000000000.00) | 89369.40000 (1000000000.00),
 [2026-01-28T22:24:00.000000000]	89437.60000 (1000000000.00) | 89437.60000 (1000000000.00),
 [2026-01-28T22:36:00.000000000]	89093.20000 (1000000000.00) | 89093.20000 (1000000000.00),
 [2026-01-28T22:59:59.000000000]	89347.10000 (1000000000.00) | 89347.10000 (1000000000.00),
 [2026-01-28T23:00:01.000000000]	89347.10000 (1000000000.00) | 89347.10000 (1000000000.00),
 [2026-01-28T23:24:00.000000000]	89433.30000 (1000000000.00) | 89433.30000 (1000000000.00),
 [2026-01-28T23:36:00.000000000]	89159.20000 (1000000000.00) | 89159.20000 (1000000000.00),
 [2026-01-28T23:59:59.000000000]	89261.70000 (1000000000.00) | 89261.70000 (1000000000.00),
 [2026-01-29T00:00:01.000000000]	89261.70000 (1000000000.00) | 89261.70000 (1000000000.00),
 [2026-01-29T00:24:00.000000000]	89316.80000 (1000000000.00) | 89316.80000 (1000000000.00),
 [2026-01-29T00:36:00.000000000]	88861.50000 (1000000000.00) | 88861.50000 (1000000000.00),
 [2026-01-29T00:59:59.000000000]	89112.00000 (1000000000.00) | 89112.00000 (1000000000.00),
 [2026-01-29T01:00:01.000000000]	89112.00000 (1000000000.00) | 89112.00000 (1000000000.00),
 [2026-01-29T01:24:00.000000000]	89130.00000 (1000000000.00) | 89130.00000 (1000000000.00),
 [2026-01-29T01:36:00.000000000]	88508.70000 (1000000000.00) | 88508.70000 (1000000000.00),
 [2026-01-29T01:59:59.000000000]	88561.70000 (1000000000.00) | 88561.70000 (1000000000.00),
 [2026-01-29T02:00:01.000000000]	88561.70000 (1000000000.00) | 88561.70000 (1000000000.00),
 [2026-01-29T02:24:00.000000000]	88721.90000 (1000000000.00) | 88721.90000 (1000000000.00),
 [2026-01-29T02:36:00.000000000]	87650.10000 (1000000000.00) | 87650.10000 (1000000000.00),
 [2026-01-29T02:59:59.000000000]	87857.90000 (1000000000.00) | 87857.90000 (1000000000.00),
 [2026-01-29T03:00:01.000000000]	87857.90000 (1000000000.00) | 87857.90000 (1000000000.00),
 [2026-01-29T03:24:00.000000000]	87723.20000 (1000000000.00) | 87723.20000 (1000000000.00),
 [2026-01-29T03:36:00.000000000]	88226.70000 (1000000000.00) | 88226.70000 (1000000000.00),
 [2026-01-29T03:59:59.000000000]	88003.20000 (1000000000.00) | 88003.20000 (1000000000.00),
 [2026-01-29T04:00:01.000000000]	88003.20000 (1000000000.00) | 88003.20000 (1000000000.00),
 [2026-01-29T04:24:00.000000000]	87863.00000 (1000000000.00) | 87863.00000 (1000000000.00),
 [2026-01-29T04:36:00.000000000]	88308.80000 (1000000000.00) | 88308.80000 (1000000000.00),
 [2026-01-29T04:59:59.000000000]	88269.90000 (1000000000.00) | 88269.90000 (1000000000.00),
 [2026-01-29T05:00:01.000000000]	88270.00000 (1000000000.00) | 88270.00000 (1000000000.00),
 [2026-01-29T05:24:00.000000000]	88378.00000 (1000000000.00) | 88378.00000 (1000000000.00),
 [2026-01-29T05:36:00.000000000]	88106.00000 (1000000000.00) | 88106.00000 (1000000000.00),
 [2026-01-29T05:59:59.000000000]	88149.30000 (1000000000.00) | 88149.30000 (1000000000.00),
 [2026-01-29T06:00:01.000000000]	88149.30000 (1000000000.00) | 88149.30000 (1000000000.00),
 [2026-01-29T06:24:00.000000000]	88133.00000 (1000000000.00) | 88133.00000 (1000000000.00),
 [2026-01-29T06:36:00.000000000]	88300.00000 (1000000000.00) | 88300.00000 (1000000000.00),
 [2026-01-29T06:59:59.000000000]	88281.10000 (1000000000.00) | 88281.10000 (1000000000.00),
 [2026-01-29T07:00:01.000000000]	88281.20000 (1000000000.00) | 88281.20000 (1000000000.00),
 [2026-01-29T07:24:00.000000000]	88211.00000 (1000000000.00) | 88211.00000 (1000000000.00),
 [2026-01-29T07:36:00.000000000]	88394.20000 (1000000000.00) | 88394.20000 (1000000000.00),
 [2026-01-29T07:59:59.000000000]	88310.90000 (1000000000.00) | 88310.90000 (1000000000.00),
 [2026-01-29T08:00:01.000000000]	88310.90000 (1000000000.00) | 88310.90000 (1000000000.00),
 [2026-01-29T08:24:00.000000000]	88461.20000 (1000000000.00) | 88461.20000 (1000000000.00),
 [2026-01-29T08:36:00.000000000]	87866.20000 (1000000000.00) | 87866.20000 (1000000000.00),
 [2026-01-29T08:59:59.000000000]	88028.10000 (1000000000.00) | 88028.10000 (1000000000.00),
 [2026-01-29T09:00:01.000000000]	88028.00000 (1000000000.00) | 88028.00000 (1000000000.00),
 [2026-01-29T09:24:00.000000000]	88120.20000 (1000000000.00) | 88120.20000 (1000000000.00),
 [2026-01-29T09:36:00.000000000]	87850.00000 (1000000000.00) | 87850.00000 (1000000000.00),
 [2026-01-29T09:59:59.000000000]	87851.10000 (1000000000.00) | 87851.10000 (1000000000.00),
 [2026-01-29T10:00:01.000000000]	87851.00000 (1000000000.00) | 87851.00000 (1000000000.00),
 [2026-01-29T10:24:00.000000000]	87773.10000 (1000000000.00) | 87773.10000 (1000000000.00),
 [2026-01-29T10:36:00.000000000]	87989.00000 (1000000000.00) | 87989.00000 (1000000000.00),
 [2026-01-29T10:59:59.000000000]	87920.10000 (1000000000.00) | 87920.10000 (1000000000.00),
 [2026-01-29T11:00:01.000000000]	87920.00000 (1000000000.00) | 87920.00000 (1000000000.00),
 [2026-01-29T11:24:00.000000000]	88027.90000 (1000000000.00) | 88027.90000 (1000000000.00),
 [2026-01-29T11:36:00.000000000]	87711.00000 (1000000000.00) | 87711.00000 (1000000000.00),
 [2026-01-29T11:59:59.000000000]	87795.20000 (1000000000.00) | 87795.20000 (1000000000.00),
 [2026-01-29T12:00:01.000000000]	87795.10000 (1000000000.00) | 87795.10000 (1000000000.00),
 [2026-01-29T12:24:00.000000000]	87775.10000 (1000000000.00) | 87775.10000 (1000000000.00),
 [2026-01-29T12:36:00.000000000]	88084.90000 (1000000000.00) | 88084.90000 (1000000000.00),
 [2026-01-29T12:59:59.000000000]	88073.80000 (1000000000.00) | 88073.80000 (1000000000.00),
 [2026-01-29T13:00:01.000000000]	88073.90000 (1000000000.00) | 88073.90000 (1000000000.00),
 [2026-01-29T13:24:00.000000000]	88133.20000 (1000000000.00) | 88133.20000 (1000000000.00),
 [2026-01-29T13:36:00.000000000]	87907.60000 (1000000000.00) | 87907.60000 (1000000000.00),
 [2026-01-29T13:59:59.000000000]	88008.80000 (1000000000.00) | 88008.80000 (1000000000.00),
 [2026-01-29T14:00:01.000000000]	88008.80000 (1000000000.00) | 88008.80000 (1000000000.00),
 [2026-01-29T14:24:00.000000000]	88035.50000 (1000000000.00) | 88035.50000 (1000000000.00),
 [2026-01-29T14:36:00.000000000]	86946.10000 (1000000000.00) | 86946.10000 (1000000000.00),
 [2026-01-29T14:59:59.000000000]	86978.70000 (1000000000.00) | 86978.70000 (1000000000.00),
 [2026-01-29T15:00:01.000000000]	86978.80000 (1000000000.00) | 86978.80000 (1000000000.00),
 [2026-01-29T15:24:00.000000000]	87013.70000 (1000000000.00) | 87013.70000 (1000000000.00),
 [2026-01-29T15:36:00.000000000]	84335.40000 (1000000000.00) | 84335.40000 (1000000000.00),
 [2026-01-29T15:59:59.000000000]	84898.00000 (1000000000.00) | 84898.00000 (1000000000.00),
 [2026-01-29T16:00:01.000000000]	84897.90000 (1000000000.00) | 84897.90000 (1000000000.00),
 [2026-01-29T16:24:00.000000000]	84222.00000 (1000000000.00) | 84222.00000 (1000000000.00),
 [2026-01-29T16:36:00.000000000]	85367.20000 (1000000000.00) | 85367.20000 (1000000000.00),
 [2026-01-29T16:59:59.000000000]	85230.30000 (1000000000.00) | 85230.30000 (1000000000.00),
 [2026-01-29T17:00:01.000000000]	85230.30000 (1000000000.00) | 85230.30000 (1000000000.00),
 [2026-01-29T17:24:00.000000000]	85596.10000 (1000000000.00) | 85596.10000 (1000000000.00),
 [2026-01-29T17:36:00.000000000]	83939.00000 (1000000000.00) | 83939.00000 (1000000000.00),
 [2026-01-29T17:59:59.000000000]	84225.00000 (1000000000.00) | 84225.00000 (1000000000.00),
 [2026-01-29T18:00:01.000000000]	84225.00000 (1000000000.00) | 84225.00000 (1000000000.00),
 [2026-01-29T18:24:00.000000000]	84595.30000 (1000000000.00) | 84595.30000 (1000000000.00),
 [2026-01-29T18:36:00.000000000]	83355.00000 (1000000000.00) | 83355.00000 (1000000000.00),
 [2026-01-29T18:59:59.000000000]	83440.90000 (1000000000.00) | 83440.90000 (1000000000.00),
 [2026-01-29T19:00:01.000000000]	83440.80000 (1000000000.00) | 83440.80000 (1000000000.00),
 [2026-01-29T19:24:00.000000000]	83338.30000 (1000000000.00) | 83338.30000 (1000000000.00),
 [2026-01-29T19:36:00.000000000]	84305.20000 (1000000000.00) | 84305.20000 (1000000000.00),
 [2026-01-29T19:59:59.000000000]	83979.40000 (1000000000.00) | 83979.40000 (1000000000.00),
 [2026-01-29T20:00:01.000000000]	83979.50000 (1000000000.00) | 83979.50000 (1000000000.00),
 [2026-01-29T20:24:00.000000000]	83785.60000 (1000000000.00) | 83785.60000 (1000000000.00),
 [2026-01-29T20:36:00.000000000]	84376.20000 (1000000000.00) | 84376.20000 (1000000000.00),
 [2026-01-29T20:59:59.000000000]	84186.30000 (1000000000.00) | 84186.30000 (1000000000.00),
 [2026-01-29T21:00:01.000000000]	84186.40000 (1000000000.00) | 84186.40000 (1000000000.00),
 [2026-01-29T21:24:00.000000000]	84169.30000 (1000000000.00) | 84169.30000 (1000000000.00),
 [2026-01-29T21:36:00.000000000]	84623.10000 (1000000000.00) | 84623.10000 (1000000000.00),
 [2026-01-29T21:59:59.000000000]	84491.00000 (1000000000.00) | 84491.00000 (1000000000.00),
 [2026-01-29T22:00:01.000000000]	84491.10000 (1000000000.00) | 84491.10000 (1000000000.00),
 [2026-01-29T22:24:00.000000000]	84271.30000 (1000000000.00) | 84271.30000 (1000000000.00),
 [2026-01-29T22:36:00.000000000]	84580.00000 (1000000000.00) | 84580.00000 (1000000000.00),
 [2026-01-29T22:59:59.000000000]	84529.60000 (1000000000.00) | 84529.60000 (1000000000.00),
 [2026-01-29T23:00:01.000000000]	84529.50000 (1000000000.00) | 84529.50000 (1000000000.00),
 [2026-01-29T23:24:00.000000000]	84400.00000 (1000000000.00) | 84400.00000 (1000000000.00),
 [2026-01-29T23:36:00.000000000]	84699.90000 (1000000000.00) | 84699.90000 (1000000000.00),
 [2026-01-29T23:59:59.000000000]	84604.70000 (1000000000.00) | 84604.70000 (1000000000.00),
 [2026-01-30T00:00:01.000000000]	84604.70000 (1000000000.00) | 84604.70000 (1000000000.00),
 [2026-01-30T00:24:00.000000000]	84697.20000 (1000000000.00) | 84697.20000 (1000000000.00),
 [2026-01-30T00:36:00.000000000]	84100.00000 (1000000000.00) | 84100.00000 (1000000000.00),
 [2026-01-30T00:59:59.000000000]	84157.40000 (1000000000.00) | 84157.40000 (1000000000.00),
 [2026-01-30T01:00:01.000000000]	84157.40000 (1000000000.00) | 84157.40000 (1000000000.00),
 [2026-01-30T01:24:00.000000000]	84157.50000 (1000000000.00) | 84157.50000 (1000000000.00),
 [2026-01-30T01:36:00.000000000]	81000.00000 (1000000000.00) | 81000.00000 (1000000000.00),
 [2026-01-30T01:59:59.000000000]	82434.70000 (1000000000.00) | 82434.70000 (1000000000.00),
 [2026-01-30T02:00:01.000000000]	82434.70000 (1000000000.00) | 82434.70000 (1000000000.00),
 [2026-01-30T02:24:00.000000000]	82514.40000 (1000000000.00) | 82514.40000 (1000000000.00),
 [2026-01-30T02:36:00.000000000]	81116.00000 (1000000000.00) | 81116.00000 (1000000000.00),
 [2026-01-30T02:59:59.000000000]	82128.10000 (1000000000.00) | 82128.10000 (1000000000.00),
 [2026-01-30T03:00:01.000000000]	82128.00000 (1000000000.00) | 82128.00000 (1000000000.00),
 [2026-01-30T03:24:00.000000000]	81995.60000 (1000000000.00) | 81995.60000 (1000000000.00),
 [2026-01-30T03:36:00.000000000]	82709.50000 (1000000000.00) | 82709.50000 (1000000000.00),
 [2026-01-30T03:59:59.000000000]	82640.90000 (1000000000.00) | 82640.90000 (1000000000.00),
 [2026-01-30T04:00:01.000000000]	82640.90000 (1000000000.00) | 82640.90000 (1000000000.00),
 [2026-01-30T04:24:00.000000000]	82640.40000 (1000000000.00) | 82640.40000 (1000000000.00),
 [2026-01-30T04:36:00.000000000]	83299.90000 (1000000000.00) | 83299.90000 (1000000000.00),
 [2026-01-30T04:59:59.000000000]	82906.60000 (1000000000.00) | 82906.60000 (1000000000.00),
 [2026-01-30T05:00:01.000000000]	82906.50000 (1000000000.00) | 82906.50000 (1000000000.00),
 [2026-01-30T05:24:00.000000000]	83300.00000 (1000000000.00) | 83300.00000 (1000000000.00),
 [2026-01-30T05:36:00.000000000]	82859.40000 (1000000000.00) | 82859.40000 (1000000000.00),
 [2026-01-30T05:59:59.000000000]	82873.50000 (1000000000.00) | 82873.50000 (1000000000.00),
 [2026-01-30T06:00:01.000000000]	82873.50000 (1000000000.00) | 82873.50000 (1000000000.00),
 [2026-01-30T06:24:00.000000000]	82882.30000 (1000000000.00) | 82882.30000 (1000000000.00),
 [2026-01-30T06:36:00.000000000]	82021.10000 (1000000000.00) | 82021.10000 (1000000000.00),
 [2026-01-30T06:59:59.000000000]	82560.80000 (1000000000.00) | 82560.80000 (1000000000.00),
 [2026-01-30T07:00:01.000000000]	82560.80000 (1000000000.00) | 82560.80000 (1000000000.00),
 [2026-01-30T07:24:00.000000000]	82431.60000 (1000000000.00) | 82431.60000 (1000000000.00),
 [2026-01-30T07:36:00.000000000]	83074.40000 (1000000000.00) | 83074.40000 (1000000000.00),
 [2026-01-30T07:59:59.000000000]	82770.10000 (1000000000.00) | 82770.10000 (1000000000.00),
 [2026-01-30T08:00:01.000000000]	82770.10000 (1000000000.00) | 82770.10000 (1000000000.00),
 [2026-01-30T08:24:00.000000000]	82939.70000 (1000000000.00) | 82939.70000 (1000000000.00),
 [2026-01-30T08:36:00.000000000]	82399.00000 (1000000000.00) | 82399.00000 (1000000000.00),
 [2026-01-30T08:59:59.000000000]	82625.30000 (1000000000.00) | 82625.30000 (1000000000.00),
 [2026-01-30T09:00:01.000000000]	82625.30000 (1000000000.00) | 82625.30000 (1000000000.00),
 [2026-01-30T09:24:00.000000000]	82793.50000 (1000000000.00) | 82793.50000 (1000000000.00),
 [2026-01-30T09:36:00.000000000]	82108.40000 (1000000000.00) | 82108.40000 (1000000000.00),
 [2026-01-30T09:59:59.000000000]	82320.50000 (1000000000.00) | 82320.50000 (1000000000.00),
 [2026-01-30T10:00:01.000000000]	82320.50000 (1000000000.00) | 82320.50000 (1000000000.00),
 [2026-01-30T10:24:00.000000000]	82115.10000 (1000000000.00) | 82115.10000 (1000000000.00),
 [2026-01-30T10:36:00.000000000]	82859.00000 (1000000000.00) | 82859.00000 (1000000000.00),
 [2026-01-30T10:59:59.000000000]	82793.20000 (1000000000.00) | 82793.20000 (1000000000.00),
 [2026-01-30T11:00:01.000000000]	82793.20000 (1000000000.00) | 82793.20000 (1000000000.00),
 [2026-01-30T11:24:00.000000000]	82626.90000 (1000000000.00) | 82626.90000 (1000000000.00),
 [2026-01-30T11:36:00.000000000]	83280.60000 (1000000000.00) | 83280.60000 (1000000000.00),
 [2026-01-30T11:59:59.000000000]	83104.80000 (1000000000.00) | 83104.80000 (1000000000.00),
 [2026-01-30T12:00:01.000000000]	83104.70000 (1000000000.00) | 83104.70000 (1000000000.00),
 [2026-01-30T12:24:00.000000000]	83296.90000 (1000000000.00) | 83296.90000 (1000000000.00),
 [2026-01-30T12:36:00.000000000]	82603.20000 (1000000000.00) | 82603.20000 (1000000000.00),
 [2026-01-30T12:59:59.000000000]	82752.80000 (1000000000.00) | 82752.80000 (1000000000.00),
 [2026-01-30T13:00:01.000000000]	82752.80000 (1000000000.00) | 82752.80000 (1000000000.00),
 [2026-01-30T13:24:00.000000000]	83062.00000 (1000000000.00) | 83062.00000 (1000000000.00),
 [2026-01-30T13:36:00.000000000]	82372.10000 (1000000000.00) | 82372.10000 (1000000000.00),
 [2026-01-30T13:59:59.000000000]	82704.90000 (1000000000.00) | 82704.90000 (1000000000.00),
 [2026-01-30T14:00:01.000000000]	82704.80000 (1000000000.00) | 82704.80000 (1000000000.00),
 [2026-01-30T14:24:00.000000000]	82693.90000 (1000000000.00) | 82693.90000 (1000000000.00),
 [2026-01-30T14:36:00.000000000]	83779.20000 (1000000000.00) | 83779.20000 (1000000000.00),
 [2026-01-30T14:59:59.000000000]	83061.40000 (1000000000.00) | 83061.40000 (1000000000.00),
 [2026-01-30T15:00:01.000000000]	83061.50000 (1000000000.00) | 83061.50000 (1000000000.00),
 [2026-01-30T15:24:00.000000000]	83577.00000 (1000000000.00) | 83577.00000 (1000000000.00),
 [2026-01-30T15:36:00.000000000]	82328.60000 (1000000000.00) | 82328.60000 (1000000000.00),
 [2026-01-30T15:59:59.000000000]	82850.20000 (1000000000.00) | 82850.20000 (1000000000.00),
 [2026-01-30T16:00:01.000000000]	82850.10000 (1000000000.00) | 82850.10000 (1000000000.00),
 [2026-01-30T16:24:00.000000000]	82504.30000 (1000000000.00) | 82504.30000 (1000000000.00),
 [2026-01-30T16:36:00.000000000]	83472.80000 (1000000000.00) | 83472.80000 (1000000000.00),
 [2026-01-30T16:59:59.000000000]	83115.20000 (1000000000.00) | 83115.20000 (1000000000.00),
 [2026-01-30T17:00:01.000000000]	83115.10000 (1000000000.00) | 83115.10000 (1000000000.00),
 [2026-01-30T17:24:00.000000000]	83450.50000 (1000000000.00) | 83450.50000 (1000000000.00),
 [2026-01-30T17:36:00.000000000]	82600.00000 (1000000000.00) | 82600.00000 (1000000000.00),
 [2026-01-30T17:59:59.000000000]	82908.00000 (1000000000.00) | 82908.00000 (1000000000.00),
 [2026-01-30T18:00:01.000000000]	82908.00000 (1000000000.00) | 82908.00000 (1000000000.00),
 [2026-01-30T18:24:00.000000000]	81832.00000 (1000000000.00) | 81832.00000 (1000000000.00),
 [2026-01-30T18:36:00.000000000]	84159.40000 (1000000000.00) | 84159.40000 (1000000000.00),
 [2026-01-30T18:59:59.000000000]	83897.30000 (1000000000.00) | 83897.30000 (1000000000.00),
 [2026-01-30T19:00:01.000000000]	83897.30000 (1000000000.00) | 83897.30000 (1000000000.00),
 [2026-01-30T19:24:00.000000000]	83875.70000 (1000000000.00) | 83875.70000 (1000000000.00),
 [2026-01-30T19:36:00.000000000]	84599.00000 (1000000000.00) | 84599.00000 (1000000000.00),
 [2026-01-30T19:59:59.000000000]	84200.00000 (1000000000.00) | 84200.00000 (1000000000.00),
 [2026-01-30T20:00:01.000000000]	84199.90000 (1000000000.00) | 84199.90000 (1000000000.00),
 [2026-01-30T20:24:00.000000000]	84275.50000 (1000000000.00) | 84275.50000 (1000000000.00),
 [2026-01-30T20:36:00.000000000]	83501.00000 (1000000000.00) | 83501.00000 (1000000000.00),
 [2026-01-30T20:59:59.000000000]	83890.30000 (1000000000.00) | 83890.30000 (1000000000.00),
 [2026-01-30T21:00:01.000000000]	83890.30000 (1000000000.00) | 83890.30000 (1000000000.00),
 [2026-01-30T21:24:00.000000000]	83759.00000 (1000000000.00) | 83759.00000 (1000000000.00),
 [2026-01-30T21:36:00.000000000]	84487.70000 (1000000000.00) | 84487.70000 (1000000000.00),
 [2026-01-30T21:59:59.000000000]	84240.30000 (1000000000.00) | 84240.30000 (1000000000.00),
 [2026-01-30T22:00:01.000000000]	84240.30000 (1000000000.00) | 84240.30000 (1000000000.00),