In [1]:
import numpy as np
import pandas as pd

import qubx  # type: ignore
import pyarrow as pa

%qubxd

%load_ext autoreload
%autoreload 2

# - - - - - - - - - -
from qubx.data.containers import RawData, RawMultiData

_mk_batch = lambda t,n: pa.RecordBatch.from_arrays([np.arange(t, t+n), np.arange(10.0 * t, 10.0 * t + n)], ["time", "value"])

⠀⠀⡰⡖⠒⠒⢒⢦⠀⠀
⠀⢠⠃⠈⢆⣀⣎⣀⣱⡀  QUBX | Quantitative Backtesting Environment
⠀⢳⠒⠒⡞⠚⡄⠀⡰⠁         (c) 2025, ver. 0.7.40.dev8
⠀⠀⠱⣜⣀⣀⣈⣦⠃⠀⠀⠀

### Common

In [2]:
pa.__version__

'15.0.2'

1. Play with pa

In [13]:
r1 = pa.RecordBatch.from_pandas(pd.DataFrame({"time": [1, 2, 3], "value": [4, 5, 6]}))
r2 = pa.RecordBatch.from_pandas(pd.DataFrame({"time": [11, 12, 13], "value": [24, 25, 26]}))

In [16]:
b1 = _mk_batch(1, 500)
b2 = _mk_batch(501, 500)
combined = pa.concat_tables([pa.Table.from_batches([b1]), pa.Table.from_batches([b2])]).combine_chunks().to_batches()[0] 
combined

pyarrow.RecordBatch
time: int64
value: double
----
time: [1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000]
value: [10,11,12,13,14,15,16,17,18,19,...,5500,5501,5502,5503,5504,5505,5506,5507,5508,5509]

### Working with Batches as some storage

In [232]:
batches = []
S = 5_000
for k in range(0, 10*S, S):
    batches.append(_mk_batch(k, S))

In [231]:
%%timeit
combined = pa.concat_tables([pa.Table.from_batches([b]) for b in batches]).combine_chunks().to_batches()[0]

56.8 μs ± 162 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [230]:
len(combined)

50000

In [ ]:
# for r in zip(*combined.to_pydict().values()):
#     break

In [ ]:
# for r in combined.to_pylist():
#     break

In [ ]:
t_c = combined.column("time").to_numpy(zero_copy_only=True)
v_c = combined.column("value").to_numpy(zero_copy_only=True)

In [238]:
_cs = 0 
for t,v in zip(t_c, v_c):
    _cs += v / (t + 1)
_cs

406444.6489152973

### RawData with nones

In [12]:
from qubx.data.transformers import OHLCVSeries, TypedRecords
from qubx.core.basics import DataType

In [13]:
raw_data = RawData.from_pandas("X", "ohlc", pd.DataFrame({
    "time":["2020-01-01", "2020-01-02", "2020-01-03"], 
    "open":  [1,2,3],
    "high":  [1,2,3],
    "low":   [3,2,1],
    "close": [1,2,None],
    "count": [None,None,None],
    "volume": [None,None,None],
}))

In [14]:
raw_data.to_pd()

            open  high  low  close count volume
time
2020-01-01     1     1    3    1.0  None   None
2020-01-02     2     2    2    2.0  None   None
2020-01-03     3     3    1    NaN  None   None

In [15]:
raw_data.to_ohlc()

            open  high  low  close  volume  bought_volume  volume_quote  \
timestamp
2020-01-01   1.0   1.0  3.0    1.0     NaN            0.0           0.0
2020-01-02   2.0   2.0  2.0    2.0     NaN            0.0           0.0
2020-01-03   3.0   3.0  1.0    NaN     NaN            0.0           0.0

            bought_volume_quote  trade_count
timestamp
2020-01-01                  0.0          0.0
2020-01-02                  0.0          0.0
2020-01-03                  0.0          0.0

In [51]:

# ok, let's review build_snapshots in /home/quant0/devs/Qubx/src/qubx/data/storages/utils.py                                       
#   it's based on list[tuple] could we use columns from record banches instead ?

In [16]:
raw_data.to_records()[0].bought_volume

0.0

In [17]:
raw_data.to_ticks(daily_session_start_end="STOCKS")

[[2020-01-01T09:30:01.100000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-01T11:00:00.000000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-01T13:00:00.000000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-01T15:59:58.900000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-02T09:30:01.100000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T11:00:00.000000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T13:00:00.000000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-02T15:59:58.900000000]	2.00000 (1000000000.00) | 2.00000 (1000000000.00),
 [2020-01-03T09:30:01.100000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-03T11:00:00.000000000]	3.00000 (1000000000.00) | 3.00000 (1000000000.00),
 [2020-01-03T13:00:00.000000000]	1.00000 (1000000000.00) | 1.00000 (1000000000.00),
 [2020-01-03T15:59:58.900000000]	nan (1000000000.00) | nan (1000000000.00)]

### RawMultiData

In [2]:
from qubx.data.containers import RawData, RawMultiData
from qubx.core.basics import DataType

In [3]:
d1 = RawData.from_pandas("X", "ohlc", pd.DataFrame({
        "y": [-1,-2,-3], "date": [1,2,3], "value": [11,22,33]
    }))
d2 = RawData.from_pandas("X2", "ohlc", pd.DataFrame({
        "y": [-1,-2,-3,0], "date": [12,22,32,55], "value": [11,22,33,99]
    }))

In [4]:
r1 = RawData.from_pandas(
    "TEST1",
    DataType.TRADE,
    pd.DataFrame({
        "price": [100,120,190], "time": [1000,2000,3000], "size": [0.5, 0.3, 1.5]
    })
)

In [5]:
dd = r1.data

In [6]:
dd.column_names

['price', 'time', 'size']

In [7]:
dm = RawMultiData([d1, d2])

In [8]:
dm.to_pd()

                                 X         X2
                                 y value    y value
date
1970-01-01 00:00:00.000000001 -1.0  11.0  NaN   NaN
1970-01-01 00:00:00.000000002 -2.0  22.0  NaN   NaN
1970-01-01 00:00:00.000000003 -3.0  33.0  NaN   NaN
1970-01-01 00:00:00.000000012  NaN   NaN -1.0  11.0
1970-01-01 00:00:00.000000022  NaN   NaN -2.0  22.0
1970-01-01 00:00:00.000000032  NaN   NaN -3.0  33.0
1970-01-01 00:00:00.000000055  NaN   NaN  0.0  99.0

In [9]:
from qubx.data.registry import StorageRegistry

In [10]:
r = StorageRegistry.get("qdb::quantlab")["BINANCE.UM", "SWAP"]

In [11]:
r.read("BTCUSDT", "ohlc(1h)", "-5d", "now").to_ticks()

[[2026-01-30T15:00:01.000000000]	83149.90000 (1000000000.00) | 83149.90000 (1000000000.00),
 [2026-01-30T15:24:00.000000000]	83338.00000 (1000000000.00) | 83338.00000 (1000000000.00),
 [2026-01-30T15:36:00.000000000]	82328.60000 (1000000000.00) | 82328.60000 (1000000000.00),
 [2026-01-30T15:59:59.000000000]	82850.20000 (1000000000.00) | 82850.20000 (1000000000.00),
 [2026-01-30T16:00:01.000000000]	82850.10000 (1000000000.00) | 82850.10000 (1000000000.00),
 [2026-01-30T16:24:00.000000000]	82504.30000 (1000000000.00) | 82504.30000 (1000000000.00),
 [2026-01-30T16:36:00.000000000]	83472.80000 (1000000000.00) | 83472.80000 (1000000000.00),
 [2026-01-30T16:59:59.000000000]	83115.20000 (1000000000.00) | 83115.20000 (1000000000.00),
 [2026-01-30T17:00:01.000000000]	83115.10000 (1000000000.00) | 83115.10000 (1000000000.00),
 [2026-01-30T17:24:00.000000000]	83450.50000 (1000000000.00) | 83450.50000 (1000000000.00),
 [2026-01-30T17:36:00.000000000]	82600.00000 (1000000000.00) | 82600.00000 (1000000000.00),
 [2026-01-30T17:59:59.000000000]	82908.00000 (1000000000.00) | 82908.00000 (1000000000.00),
 [2026-01-30T18:00:01.000000000]	82908.00000 (1000000000.00) | 82908.00000 (1000000000.00),
 [2026-01-30T18:24:00.000000000]	81832.00000 (1000000000.00) | 81832.00000 (1000000000.00),
 [2026-01-30T18:36:00.000000000]	84159.40000 (1000000000.00) | 84159.40000 (1000000000.00),
 [2026-01-30T18:59:59.000000000]	83897.30000 (1000000000.00) | 83897.30000 (1000000000.00),
 [2026-01-30T19:00:01.000000000]	83897.30000 (1000000000.00) | 83897.30000 (1000000000.00),
 [2026-01-30T19:24:00.000000000]	83875.70000 (1000000000.00) | 83875.70000 (1000000000.00),
 [2026-01-30T19:36:00.000000000]	84599.00000 (1000000000.00) | 84599.00000 (1000000000.00),
 [2026-01-30T19:59:59.000000000]	84200.00000 (1000000000.00) | 84200.00000 (1000000000.00),
 [2026-01-30T20:00:01.000000000]	84199.90000 (1000000000.00) | 84199.90000 (1000000000.00),
 [2026-01-30T20:24:00.000000000]	84275.50000 (1000000000.00) | 84275.50000 (1000000000.00),
 [2026-01-30T20:36:00.000000000]	83501.00000 (1000000000.00) | 83501.00000 (1000000000.00),
 [2026-01-30T20:59:59.000000000]	83890.30000 (1000000000.00) | 83890.30000 (1000000000.00),
 [2026-01-30T21:00:01.000000000]	83890.30000 (1000000000.00) | 83890.30000 (1000000000.00),
 [2026-01-30T21:24:00.000000000]	83759.00000 (1000000000.00) | 83759.00000 (1000000000.00),
 [2026-01-30T21:36:00.000000000]	84487.70000 (1000000000.00) | 84487.70000 (1000000000.00),
 [2026-01-30T21:59:59.000000000]	84240.30000 (1000000000.00) | 84240.30000 (1000000000.00),
 [2026-01-30T22:00:01.000000000]	84240.30000 (1000000000.00) | 84240.30000 (1000000000.00),
 [2026-01-30T22:24:00.000000000]	84291.50000 (1000000000.00) | 84291.50000 (1000000000.00),
 [2026-01-30T22:36:00.000000000]	83875.70000 (1000000000.00) | 83875.70000 (1000000000.00),
 [2026-01-30T22:59:59.000000000]	84191.10000 (1000000000.00) | 84191.10000 (1000000000.00),
 [2026-01-30T23:00:01.000000000]	84191.10000 (1000000000.00) | 84191.10000 (1000000000.00),
 [2026-01-30T23:24:00.000000000]	83897.00000 (1000000000.00) | 83897.00000 (1000000000.00),
 [2026-01-30T23:36:00.000000000]	84261.70000 (1000000000.00) | 84261.70000 (1000000000.00),
 [2026-01-30T23:59:59.000000000]	84211.40000 (1000000000.00) | 84211.40000 (1000000000.00),
 [2026-01-31T00:00:01.000000000]	84211.40000 (1000000000.00) | 84211.40000 (1000000000.00),
 [2026-01-31T00:24:00.000000000]	84239.50000 (1000000000.00) | 84239.50000 (1000000000.00),
 [2026-01-31T00:36:00.000000000]	83964.90000 (1000000000.00) | 83964.90000 (1000000000.00),
 [2026-01-31T00:59:59.000000000]	84028.10000 (1000000000.00) | 84028.10000 (1000000000.00),
 [2026-01-31T01:00:01.000000000]	84028.10000 (1000000000.00) | 84028.10000 (1000000000.00),
 [2026-01-31T01:24:00.000000000]	84227.10000 (1000000000.00) | 84227.10000 (1000000000.00),
 [2026-01-31T01:36:00.000000000]	83861.80000 (1000000000.00) | 83861.80000 (1000000000.00),
 [2026-01-31T01:59:59.000000000]	83965.90000 (1000000000.00) | 83965.90000 (1000000000.00),
 [2026-01-31T02:00:01.000000000]	83966.00000 (1000000000.00) | 83966.00000 (1000000000.00),
 [2026-01-31T02:24:00.000000000]	83775.50000 (1000000000.00) | 83775.50000 (1000000000.00),
 [2026-01-31T02:36:00.000000000]	84150.00000 (1000000000.00) | 84150.00000 (1000000000.00),
 [2026-01-31T02:59:59.000000000]	84085.60000 (1000000000.00) | 84085.60000 (1000000000.00),
 [2026-01-31T03:00:01.000000000]	84085.50000 (1000000000.00) | 84085.50000 (1000000000.00),
 [2026-01-31T03:24:00.000000000]	84190.00000 (1000000000.00) | 84190.00000 (1000000000.00),
 [2026-01-31T03:36:00.000000000]	83987.50000 (1000000000.00) | 83987.50000 (1000000000.00),
 [2026-01-31T03:59:59.000000000]	83987.50000 (1000000000.00) | 83987.50000 (1000000000.00),
 [2026-01-31T04:00:01.000000000]	83987.50000 (1000000000.00) | 83987.50000 (1000000000.00),
 [2026-01-31T04:24:00.000000000]	84110.00000 (1000000000.00) | 84110.00000 (1000000000.00),
 [2026-01-31T04:36:00.000000000]	83899.90000 (1000000000.00) | 83899.90000 (1000000000.00),
 [2026-01-31T04:59:59.000000000]	83960.40000 (1000000000.00) | 83960.40000 (1000000000.00),
 [2026-01-31T05:00:01.000000000]	83960.30000 (1000000000.00) | 83960.30000 (1000000000.00),
 [2026-01-31T05:24:00.000000000]	83861.70000 (1000000000.00) | 83861.70000 (1000000000.00),
 [2026-01-31T05:36:00.000000000]	84056.90000 (1000000000.00) | 84056.90000 (1000000000.00),
 [2026-01-31T05:59:59.000000000]	83961.80000 (1000000000.00) | 83961.80000 (1000000000.00),
 [2026-01-31T06:00:01.000000000]	83961.80000 (1000000000.00) | 83961.80000 (1000000000.00),
 [2026-01-31T06:24:00.000000000]	84012.60000 (1000000000.00) | 84012.60000 (1000000000.00),
 [2026-01-31T06:36:00.000000000]	83600.00000 (1000000000.00) | 83600.00000 (1000000000.00),
 [2026-01-31T06:59:59.000000000]	83739.10000 (1000000000.00) | 83739.10000 (1000000000.00),
 [2026-01-31T07:00:01.000000000]	83739.10000 (1000000000.00) | 83739.10000 (1000000000.00),
 [2026-01-31T07:24:00.000000000]	83759.90000 (1000000000.00) | 83759.90000 (1000000000.00),
 [2026-01-31T07:36:00.000000000]	83368.00000 (1000000000.00) | 83368.00000 (1000000000.00),
 [2026-01-31T07:59:59.000000000]	83514.40000 (1000000000.00) | 83514.40000 (1000000000.00),
 [2026-01-31T08:00:01.000000000]	83514.30000 (1000000000.00) | 83514.30000 (1000000000.00),
 [2026-01-31T08:24:00.000000000]	83598.00000 (1000000000.00) | 83598.00000 (1000000000.00),
 [2026-01-31T08:36:00.000000000]	82530.20000 (1000000000.00) | 82530.20000 (1000000000.00),
 [2026-01-31T08:59:59.000000000]	83031.10000 (1000000000.00) | 83031.10000 (1000000000.00),
 [2026-01-31T09:00:01.000000000]	83031.10000 (1000000000.00) | 83031.10000 (1000000000.00),
 [2026-01-31T09:24:00.000000000]	82850.00000 (1000000000.00) | 82850.00000 (1000000000.00),
 [2026-01-31T09:36:00.000000000]	83265.00000 (1000000000.00) | 83265.00000 (1000000000.00),
 [2026-01-31T09:59:59.000000000]	83075.30000 (1000000000.00) | 83075.30000 (1000000000.00),
 [2026-01-31T10:00:01.000000000]	83075.30000 (1000000000.00) | 83075.30000 (1000000000.00),
 [2026-01-31T10:24:00.000000000]	82880.00000 (1000000000.00) | 82880.00000 (1000000000.00),
 [2026-01-31T10:36:00.000000000]	83160.00000 (1000000000.00) | 83160.00000 (1000000000.00),
 [2026-01-31T10:59:59.000000000]	83120.90000 (1000000000.00) | 83120.90000 (1000000000.00),
 [2026-01-31T11:00:01.000000000]	83121.00000 (1000000000.00) | 83121.00000 (1000000000.00),
 [2026-01-31T11:24:00.000000000]	83121.00000 (1000000000.00) | 83121.00000 (1000000000.00),
 [2026-01-31T11:36:00.000000000]	82802.30000 (1000000000.00) | 82802.30000 (1000000000.00),
 [2026-01-31T11:59:59.000000000]	82983.20000 (1000000000.00) | 82983.20000 (1000000000.00),
 [2026-01-31T12:00:01.000000000]	82983.20000 (1000000000.00) | 82983.20000 (1000000000.00),
 [2026-01-31T12:24:00.000000000]	83115.30000 (1000000000.00) | 83115.30000 (1000000000.00),
 [2026-01-31T12:36:00.000000000]	82677.40000 (1000000000.00) | 82677.40000 (1000000000.00),
 [2026-01-31T12:59:59.000000000]	82735.60000 (1000000000.00) | 82735.60000 (1000000000.00),
 [2026-01-31T13:00:01.000000000]	82735.60000 (1000000000.00) | 82735.60000 (1000000000.00),
 [2026-01-31T13:24:00.000000000]	82888.00000 (1000000000.00) | 82888.00000 (1000000000.00),
 [2026-01-31T13:36:00.000000000]	82449.00000 (1000000000.00) | 82449.00000 (1000000000.00),
 [2026-01-31T13:59:59.000000000]	82733.00000 (1000000000.00) | 82733.00000 (1000000000.00),
 [2026-01-31T14:00:01.000000000]	82733.00000 (1000000000.00) | 82733.00000 (1000000000.00),
 [2026-01-31T14:24:00.000000000]	82898.70000 (1000000000.00) | 82898.70000 (1000000000.00),
 [2026-01-31T14:36:00.000000000]	80754.30000 (1000000000.00) | 80754.30000 (1000000000.00),
 [2026-01-31T14:59:59.000000000]	81452.50000 (1000000000.00) | 81452.50000 (1000000000.00),
 [2026-01-31T15:00:01.000000000]	81452.50000 (1000000000.00) | 81452.50000 (1000000000.00),
 [2026-01-31T15:24:00.000000000]	81760.00000 (1000000000.00) | 81760.00000 (1000000000.00),
 [2026-01-31T15:36:00.000000000]	81039.70000 (1000000000.00) | 81039.70000 (1000000000.00),
 [2026-01-31T15:59:59.000000000]	81268.60000 (1000000000.00) | 81268.60000 (1000000000.00),
 [2026-01-31T16:00:01.000000000]	81268.60000 (1000000000.00) | 81268.60000 (1000000000.00),
 [2026-01-31T16:24:00.000000000]	82200.00000 (1000000000.00) | 82200.00000 (1000000000.00),
 [2026-01-31T16:36:00.000000000]	80050.00000 (1000000000.00) | 80050.00000 (1000000000.00),
 [2026-01-31T16:59:59.000000000]	80320.90000 (1000000000.00) | 80320.90000 (1000000000.00),
 [2026-01-31T17:00:01.000000000]	80321.00000 (1000000000.00) | 80321.00000 (1000000000.00),
 [2026-01-31T17:24:00.000000000]	80506.90000 (1000000000.00) | 80506.90000 (1000000000.00),
 [2026-01-31T17:36:00.000000000]	78010.10000 (1000000000.00) | 78010.10000 (1000000000.00),
 [2026-01-31T17:59:59.000000000]	78857.10000 (1000000000.00) | 78857.10000 (1000000000.00),
 [2026-01-31T18:00:01.000000000]	78857.00000 (1000000000.00) | 78857.00000 (1000000000.00),
 [2026-01-31T18:24:00.000000000]	79100.00000 (1000000000.00) | 79100.00000 (1000000000.00),
 [2026-01-31T18:36:00.000000000]	75500.00000 (1000000000.00) | 75500.00000 (1000000000.00),
 [2026-01-31T18:59:59.000000000]	77996.80000 (1000000000.00) | 77996.80000 (1000000000.00),
 [2026-01-31T19:00:01.000000000]	77996.80000 (1000000000.00) | 77996.80000 (1000000000.00),
 [2026-01-31T19:24:00.000000000]	78527.10000 (1000000000.00) | 78527.10000 (1000000000.00),
 [2026-01-31T19:36:00.000000000]	77144.10000 (1000000000.00) | 77144.10000 (1000000000.00),
 [2026-01-31T19:59:59.000000000]	77707.90000 (1000000000.00) | 77707.90000 (1000000000.00),
 [2026-01-31T20:00:01.000000000]	77707.90000 (1000000000.00) | 77707.90000 (1000000000.00),
 [2026-01-31T20:24:00.000000000]	77037.80000 (1000000000.00) | 77037.80000 (1000000000.00),
 [2026-01-31T20:36:00.000000000]	78106.00000 (1000000000.00) | 78106.00000 (1000000000.00),
 [2026-01-31T20:59:59.000000000]	77956.70000 (1000000000.00) | 77956.70000 (1000000000.00),
 [2026-01-31T21:00:01.000000000]	77956.60000 (1000000000.00) | 77956.60000 (1000000000.00),
 [2026-01-31T21:24:00.000000000]	77323.10000 (1000000000.00) | 77323.10000 (1000000000.00),
 [2026-01-31T21:36:00.000000000]	78330.80000 (1000000000.00) | 78330.80000 (1000000000.00),
 [2026-01-31T21:59:59.000000000]	78252.40000 (1000000000.00) | 78252.40000 (1000000000.00),
 [2026-01-31T22:00:01.000000000]	78252.50000 (1000000000.00) | 78252.50000 (1000000000.00),
 [2026-01-31T22:24:00.000000000]	78443.10000 (1000000000.00) | 78443.10000 (1000000000.00),
 [2026-01-31T22:36:00.000000000]	77931.80000 (1000000000.00) | 77931.80000 (1000000000.00),
 [2026-01-31T22:59:59.000000000]	78114.50000 (1000000000.00) | 78114.50000 (1000000000.00),
 [2026-01-31T23:00:01.000000000]	78114.40000 (1000000000.00) | 78114.40000 (1000000000.00),
 [2026-01-31T23:24:00.000000000]	78023.90000 (1000000000.00) | 78023.90000 (1000000000.00),
 [2026-01-31T23:36:00.000000000]	79200.00000 (1000000000.00) | 79200.00000 (1000000000.00),
 [2026-01-31T23:59:59.000000000]	78706.80000 (1000000000.00) | 78706.80000 (1000000000.00),
 [2026-02-01T00:00:01.000000000]	78706.70000 (1000000000.00) | 78706.70000 (1000000000.00),
 [2026-02-01T00:24:00.000000000]	78600.20000 (1000000000.00) | 78600.20000 (1000000000.00),
 [2026-02-01T00:36:00.000000000]	79396.80000 (1000000000.00) | 79396.80000 (1000000000.00),
 [2026-02-01T00:59:59.000000000]	78861.20000 (1000000000.00) | 78861.20000 (1000000000.00),
 [2026-02-01T01:00:01.000000000]	78861.30000 (1000000000.00) | 78861.30000 (1000000000.00),
 [2026-02-01T01:24:00.000000000]	78906.30000 (1000000000.00) | 78906.30000 (1000000000.00),
 [2026-02-01T01:36:00.000000000]	78245.70000 (1000000000.00) | 78245.70000 (1000000000.00),
 [2026-02-01T01:59:59.000000000]	78504.80000 (1000000000.00) | 78504.80000 (1000000000.00),
 [2026-02-01T02:00:01.000000000]	78504.80000 (1000000000.00) | 78504.80000 (1000000000.00),
 [2026-02-01T02:24:00.000000000]	78339.60000 (1000000000.00) | 78339.60000 (1000000000.00),
 [2026-02-01T02:36:00.000000000]	79024.00000 (1000000000.00) | 79024.00000 (1000000000.00),
 [2026-02-01T02:59:59.000000000]	78856.40000 (1000000000.00) | 78856.40000 (1000000000.00),
 [2026-02-01T03:00:01.000000000]	78856.40000 (1000000000.00) | 78856.40000 (1000000000.00),
 [2026-02-01T03:24:00.000000000]	78971.50000 (1000000000.00) | 78971.50000 (1000000000.00),
 [2026-02-01T03:36:00.000000000]	78630.30000 (1000000000.00) | 78630.30000 (1000000000.00),
 [2026-02-01T03:59:59.000000000]	78826.30000 (1000000000.00) | 78826.30000 (1000000000.00),
 [2026-02-01T04:00:01.000000000]	78826.30000 (1000000000.00) | 78826.30000 (1000000000.00),
 [2026-02-01T04:24:00.000000000]	78680.40000 (1000000000.00) | 78680.40000 (1000000000.00),
 [2026-02-01T04:36:00.000000000]	79094.90000 (1000000000.00) | 79094.90000 (1000000000.00),
 [2026-02-01T04:59:59.000000000]	78938.10000 (1000000000.00) | 78938.10000 (1000000000.00),
 [2026-02-01T05:00:01.000000000]	78938.30000 (1000000000.00) | 78938.30000 (1000000000.00),
 [2026-02-01T05:24:00.000000000]	78970.10000 (1000000000.00) | 78970.10000 (1000000000.00),
 [2026-02-01T05:36:00.000000000]	78483.00000 (1000000000.00) | 78483.00000 (1000000000.00),
 [2026-02-01T05:59:59.000000000]	78583.90000 (1000000000.00) | 78583.90000 (1000000000.00),
 [2026-02-01T06:00:01.000000000]	78583.90000 (1000000000.00) | 78583.90000 (1000000000.00),
 [2026-02-01T06:24:00.000000000]	78791.60000 (1000000000.00) | 78791.60000 (1000000000.00),
 [2026-02-01T06:36:00.000000000]	78221.00000 (1000000000.00) | 78221.00000 (1000000000.00),
 [2026-02-01T06:59:59.000000000]	78262.90000 (1000000000.00) | 78262.90000 (1000000000.00),
 [2026-02-01T07:00:01.000000000]	78263.00000 (1000000000.00) | 78263.00000 (1000000000.00),
 [2026-02-01T07:24:00.000000000]	77899.90000 (1000000000.00) | 77899.90000 (1000000000.00),
 [2026-02-01T07:36:00.000000000]	78687.20000 (1000000000.00) | 78687.20000 (1000000000.00),
 [2026-02-01T07:59:59.000000000]	78320.80000 (1000000000.00) | 78320.80000 (1000000000.00),
 [2026-02-01T08:00:01.000000000]	78320.80000 (1000000000.00) | 78320.80000 (1000000000.00),
 [2026-02-01T08:24:00.000000000]	78213.60000 (1000000000.00) | 78213.60000 (1000000000.00),
 [2026-02-01T08:36:00.000000000]	78833.00000 (1000000000.00) | 78833.00000 (1000000000.00),
 [2026-02-01T08:59:59.000000000]	78571.30000 (1000000000.00) | 78571.30000 (1000000000.00),
 [2026-02-01T09:00:01.000000000]	78571.40000 (1000000000.00) | 78571.40000 (1000000000.00),
 [2026-02-01T09:24:00.000000000]	78511.00000 (1000000000.00) | 78511.00000 (1000000000.00),
 [2026-02-01T09:36:00.000000000]	79107.40000 (1000000000.00) | 79107.40000 (1000000000.00),
 [2026-02-01T09:59:59.000000000]	78997.00000 (1000000000.00) | 78997.00000 (1000000000.00),
 [2026-02-01T10:00:01.000000000]	78996.90000 (1000000000.00) | 78996.90000 (1000000000.00),
 [2026-02-01T10:24:00.000000000]	79194.00000 (1000000000.00) | 79194.00000 (1000000000.00),
 [2026-02-01T10:36:00.000000000]	78099.80000 (1000000000.00) | 78099.80000 (1000000000.00),
 [2026-02-01T10:59:59.000000000]	78239.90000 (1000000000.00) | 78239.90000 (1000000000.00),
 [2026-02-01T11:00:01.000000000]	78240.00000 (1000000000.00) | 78240.00000 (1000000000.00),
 [2026-02-01T11:24:00.000000000]	78240.00000 (1000000000.00) | 78240.00000 (1000000000.00),
 [2026-02-01T11:36:00.000000000]	78838.50000 (1000000000.00) | 78838.50000 (1000000000.00),
 [2026-02-01T11:59:59.000000000]	78712.10000 (1000000000.00) | 78712.10000 (1000000000.00),
 [2026-02-01T12:00:01.000000000]	78712.10000 (1000000000.00) | 78712.10000 (1000000000.00),
 [2026-02-01T12:24:00.000000000]	78724.80000 (1000000000.00) | 78724.80000 (1000000000.00),
 [2026-02-01T12:36:00.000000000]	78199.90000 (1000000000.00) | 78199.90000 (1000000000.00),
 [2026-02-01T12:59:59.000000000]	78420.60000 (1000000000.00) | 78420.60000 (1000000000.00),
 [2026-02-01T13:00:01.000000000]	78420.60000 (1000000000.00) | 78420.60000 (1000000000.00),
 [2026-02-01T13:24:00.000000000]	78732.00000 (1000000000.00) | 78732.00000 (1000000000.00),
 [2026-02-01T13:36:00.000000000]	78149.30000 (1000000000.00) | 78149.30000 (1000000000.00),
 [2026-02-01T13:59:59.000000000]	78280.70000 (1000000000.00) | 78280.70000 (1000000000.00),
 [2026-02-01T14:00:01.000000000]	78280.80000 (1000000000.00) | 78280.80000 (1000000000.00),
 [2026-02-01T14:24:00.000000000]	78500.00000 (1000000000.00) | 78500.00000 (1000000000.00),
 [2026-02-01T14:36:00.000000000]	77206.30000 (1000000000.00) | 77206.30000 (1000000000.00),
 [2026-02-01T14:59:59.000000000]	78179.40000 (1000000000.00) | 78179.40000 (1000000000.00),
 [2026-02-01T15:00:01.000000000]	78179.40000 (1000000000.00) | 78179.40000 (1000000000.00),
 [2026-02-01T15:24:00.000000000]	78220.40000 (1000000000.00) | 78220.40000 (1000000000.00),
 [2026-02-01T15:36:00.000000000]	76752.50000 (1000000000.00) | 76752.50000 (1000000000.00),
 [2026-02-01T15:59:59.000000000]	77563.80000 (1000000000.00) | 77563.80000 (1000000000.00),
 [2026-02-01T16:00:01.000000000]	77563.80000 (1000000000.00) | 77563.80000 (1000000000.00),
 [2026-02-01T16:24:00.000000000]	77813.70000 (1000000000.00) | 77813.70000 (1000000000.00),
 [2026-02-01T16:36:00.000000000]	77056.70000 (1000000000.00) | 77056.70000 (1000000000.00),
 [2026-02-01T16:59:59.000000000]	77459.20000 (1000000000.00) | 77459.20000 (1000000000.00),
 [2026-02-01T17:00:01.000000000]	77459.20000 (1000000000.00) | 77459.20000 (1000000000.00),
 [2026-02-01T17:24:00.000000000]	77259.50000 (1000000000.00) | 77259.50000 (1000000000.00),
 [2026-02-01T17:36:00.000000000]	77721.50000 (1000000000.00) | 77721.50000 (1000000000.00),
 [2026-02-01T17:59:59.000000000]	77711.00000 (1000000000.00) | 77711.00000 (1000000000.00),
 [2026-02-01T18:00:01.000000000]	77711.10000 (1000000000.00) | 77711.10000 (1000000000.00),
 [2026-02-01T18:24:00.000000000]	77689.10000 (1000000000.00) | 77689.10000 (1000000000.00),
 [2026-02-01T18:36:00.000000000]	78421.60000 (1000000000.00) | 78421.60000 (1000000000.00),
 [2026-02-01T18:59:59.000000000]	77995.90000 (1000000000.00) | 77995.90000 (1000000000.00),
 [2026-02-01T19:00:01.000000000]	77995.90000 (1000000000.00) | 77995.90000 (1000000000.00),
 [2026-02-01T19:24:00.000000000]	78073.90000 (1000000000.00) | 78073.90000 (1000000000.00),
 [2026-02-01T19:36:00.000000000]	76950.90000 (1000000000.00) | 76950.90000 (1000000000.00),
 [2026-02-01T19:59:59.000000000]	77142.40000 (1000000000.00) | 77142.40000 (1000000000.00),
 [2026-02-01T20:00:01.000000000]	77142.40000 (1000000000.00) | 77142.40000 (1000000000.00),
 [2026-02-01T20:24:00.000000000]	77708.20000 (1000000000.00) | 77708.20000 (1000000000.00),
 [2026-02-01T20:36:00.000000000]	76543.70000 (1000000000.00) | 76543.70000 (1000000000.00),
 [2026-02-01T20:59:59.000000000]	77073.50000 (1000000000.00) | 77073.50000 (1000000000.00),
 [2026-02-01T21:00:01.000000000]	77073.60000 (1000000000.00) | 77073.60000 (1000000000.00),